#!/usr/bin/env python3
"""Run log analyzer from a checkout without installing it: ./logan --help"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.realpath(__file__)), 'src'))

from log_analyzer.cli import main  # noqa: E402

sys.exit(main())
